### ISSUE TITLE
Error with class R

### ISSUE THREAD

**Issue by bukosabino** [jcesarmobile/FileBrowserAndroidTest#1]
Hi, I have problems with the cordova filechooser for Android 4.4.

I compile this project (jcesarmobile) or install cesidiobenedetto plugin https://github.com/cdibened/filechooser and I have same errors with R class:

-compile:
/home/bukosabino/cordova_projects/ionic_hello_client/platforms/android/src/com/cesidiodibenedetto/filechooser/FileChooser.java:42: error: cannot find symbol
target, this.cordova.getActivity().getString(R.string.chooser_title));
[javac]   symbol:   variable chooser_title
[javac]   location: class string

I have 9 errors, one for each use of the class R, what I can do? Thank you!

**Comment by jcesarmobile** [comment]
My sample project should run just downloading it, with no changes

For cesidiobenedetto plugin, read his readme

Configuration

You will have to import your.package.name.R into the following java files.

```
FileChooser.java 
FileChooserActivity.java 
FileListAdapter.java
FileListFragment.java
LocalStorageProvider.java
```

**Comment by snwalkunde** [comment]
I am also getting same issue.. is there any solution for this?

**Comment by jcesarmobile** [comment]
can you give more details?

Do you get that problem when you use my sample project or when you try to use the plugin in your own project?

**Comment by nancydrew123** [comment]
Hi,
I am facing the same problem, when i try to use the plugin in phonegap application . How tto import the .R file to the corresponding .java files. Please provide some suggestions.

**Comment by jcesarmobile** [comment]
I already provided the details in previous comments.
Anyway, this is a sample project with the plugin added. For problems with the plugin ask on the plugin page.

**Comment by nancydrew123** [comment]
Hi,
Thank you for the fast response. I had imported it, and i am getting the same error message. But I am having a query wehther its possible to build in "phonegap.build.com", because i m getting the same error in phonegap build also. if possible how to import the package in build site.

Kindly help us. Looking forward for your reply

**Comment by jcesarmobile** [comment]
No, it can't be used on phonegap build because you can't edit that files on phonegap build.

You can fork the plugin, edit those files using your app package, and then use your fork instead of the original plugin

**Comment by nancydrew123** [comment]
Hi,

Thank You for the response. Can you please provide me a sample of
config.xml which says how to add the fork plugin in config.xml. I am
unfamiliar of adding fork plugin in cnfig.xml.  It will be really helpful
for us.

Thanks

**Comment by jcesarmobile** [comment]
Read this blog post to figure out how to install plugins from github
http://phonegap.com/blog/2016/02/16/git-plugins/

**Comment by nancydrew123** [comment]
Hi,

Thank you for your quick response. Your suggestion help me a lot to find the solution for the problem. I was troubling with this issue for days. Once again thank you so much

Thanks
